Index: acpid-2.0.6/Makefile
===================================================================
--- acpid-2.0.6.orig/Makefile
+++ acpid-2.0.6/Makefile
@@ -31,8 +31,9 @@ MAN8GZ = $(MAN8:.8=.8.gz)
 
 DOCS = COPYING Changelog README TESTPLAN TODO 
 
-CFLAGS = -W -Wall -Werror -Wundef -Wshadow -D_GNU_SOURCE $(OPT) \
-	-fno-strict-aliasing -g $(DEFS)
+CFLAGS += -W -Wall -Werror -Wundef -Wshadow -D_GNU_SOURCE \
+	-fno-strict-aliasing $(DEFS) -fPIE
+LDFLAGS += -pie
 DEFS = -DVERSION="\"$(VERSION)\""
 
 all: $(PROGS)
