diff -ur bootsplash-3.3.orig/Utilities/Makefile bootsplash-3.3/Utilities/Makefile
--- bootsplash-3.3.orig/Utilities/Makefile	2004-09-23 19:28:38.000000000 +0300
+++ bootsplash-3.3/Utilities/Makefile	2007-03-12 01:36:04.282165436 +0200
@@ -22,7 +22,7 @@
 LIBSS_FT2    = $(LIBDIR)/libfreetype.a $(LIBDIR)/libz.a -lm
 LIBSD_FT2    = -lfreetype -lm
 
-LIBSS_MNG    = $(LIBDIR)/libmng-mini.a $(LIBDIR)/libz.a -lm
+LIBSS_MNG    = $(LIBDIR)/libmng.a $(LIBDIR)/libz.a -lm
 LIBSD_MNG    = -lmng -lz -lm
 
 CFLAGS   = -Os -Wall -I/usr/include/freetype2
@@ -40,7 +40,7 @@
 	-rm -f $(PROGRAMS) $(PROGRAMS_STATIC)
 
 splash: splash.o
-	$(LINKD) $(LDFLAGS) splash.o $(LIBDIR)/libmng-mini.a -lz -lm
+	$(LINKD) $(LDFLAGS) splash.o -lmng -lz -lm -ljpeg -llcms
 
 fbtruetype: $(OBJECTS_FT2) 
 	@rm -f fbtruetype
