'\" t
.\"     Title: perf-lock
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/05/2012
.\"    Manual: perf Manual
.\"    Source: perf 3.2.0
.\"  Language: English
.\"
.TH "PERF\-LOCK" "1" "01/05/2012" "perf 3\&.2\&.0" "perf Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
perf-lock \- Analyze lock events
.SH "SYNOPSIS"
.sp
.nf
\fIperf lock\fR {record|report|trace}
.fi
.SH "DESCRIPTION"
.sp
You can analyze various lock behaviours and statistics with this \fIperf lock\fR command\&.
.sp
.if n \{\
.RS 4
.\}
.nf
\*(Aqperf lock record <command>\*(Aq records lock events
between start and end <command>\&. And this command
produces the file "perf\&.data" which contains tracing
results of lock events\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\*(Aqperf lock trace\*(Aq shows raw lock events\&.
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
\*(Aqperf lock report\*(Aq reports statistical data\&.
.fi
.if n \{\
.RE
.\}
.SH "COMMON OPTIONS"
.PP
\-i, \-\-input=<file>
.RS 4
Input file name\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Be more verbose (show symbol address, etc)\&.
.RE
.PP
\-D, \-\-dump\-raw\-trace
.RS 4
Dump raw trace in ASCII\&.
.RE
.SH "REPORT OPTIONS"
.PP
\-k, \-\-key=<value>
.RS 4
Sorting key\&. Possible values: acquired (default), contended, wait_total, wait_max, wait_min\&.
.RE
.SH "SEE ALSO"
.sp
\fBperf\fR(1)
