Index: compat-wireless-2.6.38-3-ns/Makefile
===================================================================
--- compat-wireless-2.6.38-3-ns.orig/Makefile
+++ compat-wireless-2.6.38-3-ns/Makefile
@@ -89,7 +89,6 @@ btinstall: btuninstall bt-install-module
 bt-install-modules: bt
 	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) BT=TRUE \
 		modules_install
-	@/sbin/depmod -ae
 	@echo
 	@echo "Currently detected bluetooth subsystem modules:"
 	@echo
@@ -125,9 +124,6 @@ btuninstall:
 	@# New location, matches upstream
 	@rm -rf $(KLIB)/$(KMODDIR)/net/bluetooth/
 	@rm -rf $(KLIB)/$(KMODDIR)/drivers/bluetooth/
-	@# Lets only remove the stuff we are sure we are providing
-	@# on the misc directory.
-	@/sbin/depmod -ae
 	@echo
 	@echo "Your old bluetooth subsystem modules were left intact:"
 	@echo
@@ -157,12 +153,11 @@ btclean:
 	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) BT=TRUE clean
 	@rm -f $(CREL_PRE)*
 
-install: uninstall install-modules install-scripts
+install: install-modules
 
 install-modules: modules
 	$(MAKE) -C $(KLIB_BUILD) M=$(PWD) $(KMODDIR_ARG) $(KMODPATH_ARG) \
 		modules_install
-	@./scripts/update-initramfs
 
 install-scripts:
 	@# All the scripts we can use
@@ -194,19 +189,8 @@ install-scripts:
 		echo Running iwl-enable iwlagn...;\
 		/usr/sbin/iwl-enable iwlagn ;\
 	fi
-	@# If on distributions like Mandriva which like to
-	@# compress their modules this will find out and do
-	@# it for you. Reason is some old version of modutils
-	@# won't know mac80211.ko should be used instead of
-	@# mac80211.ko.gz
-	@./scripts/compress_modules
-	@# Mandrake doesn't have a depmod.d/ conf file to prefer
-	@# the updates/ dir which is what we use so we add one for it
-	@# (or any other distribution that doens't have this).
-	@./scripts/check_depmod
 	@# Udev stuff needed for the new compat_firmware_class.
 	@./compat/scripts/compat_firmware_install
-	@/sbin/depmod -a
 	@echo
 	@echo "Currently detected wireless subsystem modules:"
 	@echo 
@@ -337,7 +321,6 @@ uninstall:
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/misc/eeprom/eeprom_93cx6.ko*
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/misc/eeprom_93cx6.ko*
 	@rm -f $(KLIB)/$(KMODDIR)/drivers/net/b44.ko*
-	@/sbin/depmod -a
 	@echo
 	@echo "Your old wireless subsystem modules were left intact:"
 	@echo 
Index: compat-wireless-2.6.38-3-ns/scripts/gen-compat-autoconf.sh
===================================================================
--- compat-wireless-2.6.38-3-ns.orig/scripts/gen-compat-autoconf.sh
+++ compat-wireless-2.6.38-3-ns/scripts/gen-compat-autoconf.sh
@@ -184,7 +184,8 @@ done
 # Deal with special cases. CONFIG_MAC80211_QOS is such a case.
 # We handle this specially for different kernels we support.
 if [ -f $KLIB_BUILD/Makefile ]; then
-	SUBLEVEL=$(make -C $KLIB_BUILD kernelversion | sed -n 's/^2\.6\.\([0-9]\+\).*/\1/p')
+    # Use our own version string, other method causes sandbox violations
+	SUBLEVEL=$(echo "@KERNELRELEASE@" | sed -n 's/^2\.6\.\([0-9]\+\).*/\1/p')
 	if [ $SUBLEVEL -le 22 ]; then
 		define_config CONFIG_MAC80211_QOS y
 	else # kernel >= 2.6.23
