'\" t
.\"     Title: eggdbus-binding-tool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: December 2008
.\"    Manual: eggdbus-binding-tool
.\"    Source: EggDBus
.\"  Language: English
.\"
.TH "EGGDBUS\-BINDING\-TO" "1" "December 2008" "EggDBus" "eggdbus-binding-tool"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
eggdbus-binding-tool \- EggDBus binding tool
.SH "SYNOPSIS"
.HP \w'\fBeggdbus\-binding\-tool\fR\ 'u
\fBeggdbus\-binding\-tool\fR [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
TODO: Write me\&.
.SH "SEE ALSO"
.PP

\fBdbus-send\fR(1),
\fBdbus-daemon\fR(1)
