'\" t
.\"     Title: perf-annotate
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 08/12/2010
.\"    Manual: perf Manual
.\"    Source: perf 2.6.35.1-141
.\"  Language: English
.\"
.TH "PERF\-ANNOTATE" "1" "08/12/2010" "perf 2\&.6\&.35\&.1\-141" "perf Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
perf-annotate \- Read perf\&.data (created by perf record) and display annotated code
.SH "SYNOPSIS"
.sp
.nf
\fIperf annotate\fR [\-i <file> | \-\-input=file] symbol_name
.fi
.SH "DESCRIPTION"
.sp
This command reads the input file and displays an annotated version of the code\&. If the object file has debug symbols then the source code will be displayed alongside assembly code\&.
.sp
If there is no debug info in the object, then annotated assembly is displayed\&.
.SH "OPTIONS"
.PP
\-i, \-\-input=
.RS 4
Input file name\&. (default: perf\&.data)
.RE
.SH "SEE ALSO"
.sp
\fBperf-record\fR(1)
