diff -Nuar acpi4asus-0.41.orig/Makefile acpi4asus-0.41/Makefile
--- acpi4asus-0.41.orig/Makefile	2007-05-05 17:57:07.000000000 +0300
+++ acpi4asus-0.41/Makefile	2008-03-30 13:08:38.000000000 +0300
@@ -11,14 +11,12 @@
 all: build
 
 build:
-	make -C driver
 	make -C asus_acpid
 
 install:
 	@if [ `id -ur` != 0 ]; then \
 		echo $(ROOTMSG); \
 	else \
-		make -C driver install ; \
 		make -C asus_acpid install ; \
 		echo ""; \
 		echo ""; \
@@ -28,6 +26,5 @@
 	fi
 
 clean:
-	make -C driver clean
 	make -C asus_acpid clean
 
