#! /bin/sh
#
# Tiny startup wrapper for the Eclipse 3.0.x series
#
# Copyright (c) 2004, Karl Trygve Kalleberg <karltk@gentoo.org>
# Copyright (c) 2004, Gentoo Foundation
#
# Licensed under the GNU General Public License, version 2
#

if [ -f $HOME/.eclipserc ] ; then
	. $HOME/.eclipserc
fi

if [ -z "${ECLIPSE_HOME}" ] ; then
	ECLIPSE_HOME=/opt/eclipse
	ECLIPSE_BIN=${ECLIPSE_HOME}/eclipse
fi

if [ ! -x ${ECLIPSE_BIN} ] ; then
	echo "Failed to find executable '${ECLIPSE_BIN}'" > /dev/stderr
	exit -1
fi

# Remove the exporting of this env. because it prevents eclipse starting up gracefully
# In Pardus, we don't hit the issues mentioned below:
# Fix upstream  buttons not being clickable bug reportes as  #290395, #291257
# export GDK_NATIVE_WINDOWS=true

# Showing libxul.so to the eclipse, so it's able to start intro view that needs to utilize
# from browser related functionalities located in the library
${ECLIPSE_BIN} -vmargs -Dorg.eclipse.swt.browser.XULRunnerPath=/usr/lib/xulrunner-2.0.0  $@ 
