'\" t
.\"     Title: perf-buildid-list
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/27/2010
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PERF\-BUILDID\-LIST" "1" "12/27/2010" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
perf-buildid-list \- List the buildids in a perf\&.data file
.SH "SYNOPSIS"
.sp
.nf
\fIperf buildid\-list <options>\fR
.fi
.SH "DESCRIPTION"
.sp
This command displays the buildids found in a perf\&.data file, so that other tools can be used to fetch packages with matching symbol tables for use by perf report\&.
.SH "OPTIONS"
.PP
\-i, \-\-input=
.RS 4
Input file name\&. (default: perf\&.data)
.RE
.PP
\-f, \-\-force
.RS 4
Don\(cqt do ownership validation\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Be more verbose\&.
.RE
.SH "SEE ALSO"
.sp
\fBperf-record\fR(1), \fBperf-top\fR(1), \fBperf-report\fR(1)
